package com.example.bigwork.service;
import com.example.bigwork.dto.*;import com.example.bigwork.exception.BusinessException;import com.example.bigwork.model.*;import com.example.bigwork.repository.*;import com.example.bigwork.support.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.LocalDateTime;import java.util.*;
@Service
public class ForumService{
 private final ForumTopicRepository topics;private final ForumPostRepository posts;private final UserRepository users;private final ForumInteractionRepository interactions;
 public ForumService(ForumTopicRepository t,ForumPostRepository p,UserRepository u,ForumInteractionRepository i){topics=t;posts=p;users=u;interactions=i;}
 @Transactional(readOnly=true) public List<ForumTopicResponse> listTopics(SessionUser user,String keyword,String category,boolean favorites){
  return topics.findAll().stream().filter(t->keyword==null||keyword.isBlank()||t.getTitle().toLowerCase().contains(keyword.toLowerCase())||(t.getDescription()!=null&&t.getDescription().toLowerCase().contains(keyword.toLowerCase())))
   .filter(t->category==null||category.isBlank()||category.equals(t.getCategory())).map(t->response(t,user)).filter(t->!favorites||t.favorited()).sorted(Comparator.comparing(ForumTopicResponse::updatedAt).reversed()).toList();}
 private ForumTopicResponse response(ForumTopic t,SessionUser user){List<ForumInteraction> rows=interactions.findByTopicId(t.getId());ForumInteraction mine=user==null?null:rows.stream().filter(x->x.getUserId().equals(user.getId())).findFirst().orElse(null);return new ForumTopicResponse(t.getId(),t.getTitle(),t.getDescription(),t.getCategory()==null?"备考交流":t.getCategory(),author(t.getAuthorId()),DateTimeUtils.format(t.getCreatedAt()),DateTimeUtils.format(t.getUpdatedAt()),rows.stream().filter(ForumInteraction::isLiked).count(),rows.stream().filter(ForumInteraction::isFavorited).count(),mine!=null&&mine.isLiked(),mine!=null&&mine.isFavorited(),user!=null&&(Objects.equals(t.getAuthorId(),user.getId())||"admin".equalsIgnoreCase(user.getRole())));}
 @Transactional public Long createTopic(CreateForumTopicRequest r,SessionUser u){login(u);ForumTopic t=new ForumTopic();t.setTitle(r.title());t.setDescription(r.description());t.setCategory(r.category()==null||r.category().isBlank()?"备考交流":r.category());t.setAuthorId(u.getId());t.setCreatedAt(LocalDateTime.now());t.setUpdatedAt(LocalDateTime.now());return topics.save(t).getId();}
 @Transactional(readOnly=true) public List<ForumPostResponse> listPosts(Long id){return posts.findByTopicIdOrderByCreatedAtAsc(id).stream().map(p->new ForumPostResponse(p.getId(),p.getContent(),author(p.getAuthorId()),DateTimeUtils.format(p.getCreatedAt()),DateTimeUtils.format(p.getUpdatedAt()))).toList();}
 @Transactional public Long createPost(Long id,CreateForumPostRequest r,SessionUser u){login(u);ForumTopic t=topics.findById(id).orElseThrow(()->new BusinessException(HttpStatus.NOT_FOUND,"话题不存在"));ForumPost p=new ForumPost();p.setTopicId(id);p.setAuthorId(u.getId());p.setContent(r.content());p.setCreatedAt(LocalDateTime.now());p.setUpdatedAt(LocalDateTime.now());t.setUpdatedAt(LocalDateTime.now());topics.save(t);return posts.save(p).getId();}
 @Transactional public Map<String,Boolean> toggle(Long id,String action,SessionUser u){login(u);topics.findById(id).orElseThrow(()->new BusinessException(HttpStatus.NOT_FOUND,"话题不存在"));ForumInteraction i=interactions.findByTopicIdAndUserId(id,u.getId()).orElseGet(ForumInteraction::new);i.setTopicId(id);i.setUserId(u.getId());if("like".equals(action))i.setLiked(!i.isLiked());else if("favorite".equals(action))i.setFavorited(!i.isFavorited());else throw new BusinessException(HttpStatus.BAD_REQUEST,"不支持的操作");interactions.save(i);return Map.of("liked",i.isLiked(),"favorited",i.isFavorited());}
 @Transactional public void deleteTopic(Long id,SessionUser u){login(u);ForumTopic t=topics.findById(id).orElseThrow(()->new BusinessException(HttpStatus.NOT_FOUND,"话题不存在"));if(!Objects.equals(t.getAuthorId(),u.getId())&&!"admin".equalsIgnoreCase(u.getRole()))throw new BusinessException(HttpStatus.FORBIDDEN,"只能删除自己的话题");posts.deleteAll(posts.findByTopicIdOrderByCreatedAtAsc(id));interactions.deleteByTopicId(id);topics.delete(t);}
 private void login(SessionUser u){if(u==null)throw new BusinessException(HttpStatus.UNAUTHORIZED,"请先登录");}private String author(Long id){return id==null?"匿名用户":users.findById(id).map(User::getDisplayName).orElse("用户已删除");}
}
