spring.application.name=bigwork-server

server.port=${PORT:8080}

spring.datasource.url=${DB_URL:jdbc:h2:file:./data/bigwork;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH}
spring.datasource.username=${DB_USER:sa}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.mvc.problemdetails.enabled=true
server.servlet.session.timeout=2h
