import dayjs from 'dayjs';

export const majorsSeed = [
  {
    id: 'major_cs',
    name: '计算机科学与技术',
    description: '涵盖数据结构、计算机组成原理、操作系统与计算机网络的系统备考路径。',
  },
  {
    id: 'major_math',
    name: '应用数学',
    description: '专注高等数学、线性代数与概率统计的强化与冲刺训练。',
  },
  {
    id: 'major_english',
    name: '英语语言文学',
    description: '从基础语法到写作实战，兼顾翻译与写作能力提升。',
  },
  {
    id: 'major_management',
    name: '工商管理',
    description: '管理类联考数学、逻辑与写作的全阶段复习方案。',
  },
];

export const usersSeed = [
  {
    id: 'user_student_1',
    username: 'student',
    password: 'study2025',
    display_name: '张同学',
    role: 'student',
    email: 'student@example.com',
    phone: '13800001234',
    organization: '北京理工大学 · 计算机专硕',
    goal: '冲刺 2025 统考 390+ 分',
    major_id: 'major_cs',
    avatar: '张',
    bio: '目标院校：北京理工大学；擅长英语阅读，需强化 408 图论与操作系统。',
  },
  {
    id: 'user_admin_1',
    username: 'admin',
    password: 'admin123',
    display_name: '李老师',
    role: 'admin',
    email: 'admin@example.com',
    phone: '13500004567',
    organization: '研学进阶教研组',
    goal: '统筹课程与题库质量，保障教研节奏。',
    major_id: 'major_cs',
    avatar: '李',
    bio: '负责数学、英语与专业课教研统筹，擅长课程建设与教学服务。',
  },
];

export const coursesSeed = [
  {
    id: 'course_algo',
    major_id: 'major_cs',
    name: '408 数据结构强化班',
    category: '专业课',
    teacher: '张老师',
    credit: 4,
    progress: 62,
    status: 'published',
    summary: '深度讲解图论、动态规划等高频考点，配套题单与解析。',
    schedule_info: '每周三晚 19:00 直播',
    release_window: '2024.06-2024.09',
  },
  {
    id: 'course_math',
    major_id: 'major_math',
    name: '数学一冲刺直播营',
    category: '公共课',
    teacher: '王老师',
    credit: 3,
    progress: 48,
    status: 'published',
    summary: '针对高数、线代难点的冲刺突破课程，结合模考试卷讲评。',
    schedule_info: '每周末 09:00-12:00',
    release_window: '2024.05-2024.10',
  },
  {
    id: 'course_english',
    major_id: 'major_english',
    name: '英语一写作密训营',
    category: '公共课',
    teacher: '刘老师',
    credit: 2,
    progress: 71,
    status: 'published',
    summary: '模板搭建、真题拆解与批改反馈结合的写作提升计划。',
    schedule_info: '每周二、周四晚 20:00',
    release_window: '2024.04-2024.08',
  },
  {
    id: 'course_politics',
    major_id: 'major_management',
    name: '政治热点全掌握',
    category: '公共课',
    teacher: '肖老师',
    credit: 2,
    progress: 35,
    status: 'draft',
    summary: '覆盖当年时政热点与分析框架，搭配押题模拟。',
    schedule_info: '待排期',
    release_window: '2024.07-2024.11',
  },
  {
    id: 'course_ai',
    major_id: 'major_cs',
    name: 'AI 赋能考研算法专题',
    category: '专业课',
    teacher: '周老师',
    credit: 2,
    progress: 15,
    status: 'review',
    summary: '以算法题为主线，结合 AI 批改与诊断，强化薄弱知识点。',
    schedule_info: '计划 8 月上线',
    release_window: '2024.08-2024.10',
  },
];

export const materialsSeed = [
  {
    id: 'material_algo_outline',
    course_id: 'course_algo',
    title: '数据结构图论拔高讲义',
    material_type: '讲义',
    url: 'https://example.com/materials/graph-outline.pdf',
    description: '包含最短路、最小生成树与拓扑排序的重点题型分析。',
  },
  {
    id: 'material_algo_problem',
    course_id: 'course_algo',
    title: '算法强化题单（含解析）',
    material_type: '题单',
    url: 'https://example.com/materials/algo-problem-set.pdf',
    description: '精选 40 道历年真题与模拟题，覆盖图、树、动态规划。',
  },
  {
    id: 'material_math_notes',
    course_id: 'course_math',
    title: '线代冲刺公式速查表',
    material_type: '资料',
    url: 'https://example.com/materials/linear-algebra-cheatsheet.pdf',
    description: '线性代数高频考点与常见陷阱总结。',
  },
  {
    id: 'material_english_templates',
    course_id: 'course_english',
    title: '大作文万能模板与素材库',
    material_type: '资料',
    url: 'https://example.com/materials/english-writing-pack.pdf',
    description: '包含 12 篇高分范文、开头结尾模板与热点素材。',
  },
];

export const practiceSetsSeed = () => [
  {
    id: 'practice_algo_strength',
    owner_id: 'user_student_1',
    name: '强化算法与数据结构薄弱点',
    focus: '图论、动态规划、并查集',
    difficulty: '进阶',
    duration_minutes: 45,
    question_count: 0,
    last_attempt_at: dayjs().subtract(2, 'day').toISOString(),
    last_accuracy: 0.68,
    last_score: 68,
    last_summary: '上次训练正确 17/25 题，图论最短路与并查集题型存在失误。',
    source: 'AI 诊断生成',
  },
  {
    id: 'practice_politics_hot',
    owner_id: 'user_student_1',
    name: '政治热点主观题精练',
    focus: '时政热点、主观题作答结构',
    difficulty: '冲刺',
    duration_minutes: 35,
    question_count: 0,
    last_attempt_at: dayjs().subtract(4, 'day').toISOString(),
    last_accuracy: 0.62,
    last_score: 74,
    last_summary: '模拟题写作结构合理，需加强时政案例积累。',
    source: '系统推荐',
  },
  {
    id: 'practice_english_reading',
    owner_id: 'user_student_1',
    name: '英语一阅读理解巩固',
    focus: '长难句、细节题定位',
    difficulty: '基础',
    duration_minutes: 30,
    question_count: 0,
    last_attempt_at: dayjs().subtract(6, 'day').toISOString(),
    last_accuracy: 0.82,
    last_score: 82,
    last_summary: '细节题正确率高，主旨题需关注逻辑连接词。',
    source: '系统推荐',
  },
];

export const practiceQuestionsSeed = [
  {
    id: 'q_algo_01',
    practice_set_id: 'practice_algo_strength',
    question_type: 'single',
    stem: '设有一个含 n 个顶点的连通无向图，使用 Prim 算法求最小生成树时，采用邻接矩阵存储，使用最小堆维护横切边集合，则算法的时间复杂度是？',
    options_json: JSON.stringify(['O(n^2)', 'O(n log n)', 'O((n + m) log n)', 'O(m log n)']),
    correct_options: JSON.stringify([2]),
    explanation: '采用最小堆后，Prim 算法的时间复杂度为 O((n + m) log n)，对稠密图近似为 O(n^2 log n)。',
    knowledge_point: '最小生成树',
  },
  {
    id: 'q_algo_02',
    practice_set_id: 'practice_algo_strength',
    question_type: 'multiple',
    stem: '关于并查集（Union-Find）结构的描述，正确的有？',
    options_json: JSON.stringify([
      '按秩合并可以减小树的高度',
      '路径压缩可以将查找操作的时间复杂度降低到 O(1)',
      '启用路径压缩后最坏情况下仍可能退化到链表',
      '按秩合并与路径压缩配合时，单次操作的均摊复杂度接近 O(α(n))',
    ]),
    correct_options: JSON.stringify([0, 3]),
    explanation: '按秩合并与路径压缩结合时，单次操作的均摊复杂度为 O(α(n))，路径压缩可大幅降低高度但不是绝对 O(1)。',
    knowledge_point: '并查集',
  },
  {
    id: 'q_algo_03',
    practice_set_id: 'practice_algo_strength',
    question_type: 'single',
    stem: '在 Dijkstra 算法中，若采用邻接表存储图并使用二叉堆，算法的时间复杂度是？',
    options_json: JSON.stringify(['O(n^2)', 'O(n log n + m)', 'O(m log n)', 'O(n + m log n)']),
    correct_options: JSON.stringify([2]),
    explanation: 'Dijkstra 算法使用二叉堆时的时间复杂度为 O(m log n)。',
    knowledge_point: '最短路径',
  },
  {
    id: 'q_algo_04',
    practice_set_id: 'practice_algo_strength',
    question_type: 'multiple',
    stem: '以下关于拓扑排序的说法正确的是：',
    options_json: JSON.stringify([
      '拓扑排序适用于有向无环图（DAG）',
      '拓扑排序的结果可能不唯一',
      '若图中存在环，则无法得到拓扑序',
      '拓扑排序可用于检测无向图是否存在环',
    ]),
    correct_options: JSON.stringify([0, 1, 2]),
    explanation: '拓扑排序只适用于 DAG；若存在环则无法得到拓扑序；结果可能不唯一。',
    knowledge_point: '拓扑排序',
  },
  {
    id: 'q_algo_05',
    practice_set_id: 'practice_algo_strength',
    question_type: 'single',
    stem: '对于一个使用邻接表存储的图，采用 BFS 判断图中是否存在长度为 k 的最短路径，算法的时间复杂度主要取决于：',
    options_json: JSON.stringify(['顶点数 n', '边数 m', 'k 的大小', '与图的连通分支数量无关']),
    correct_options: JSON.stringify([1]),
    explanation: 'BFS 的复杂度主要取决于边数 m；k 只影响遍历深度，但不会改变量级。',
    knowledge_point: '图的遍历',
  },
  {
    id: 'q_algo_06',
    practice_set_id: 'practice_algo_strength',
    question_type: 'single',
    stem: '在动态规划求解背包问题时，若容量 W 与物品个数 n 均较大，下列优化方法更适合的是？',
    options_json: JSON.stringify(['完全背包优化', '分组背包优化', '状态压缩或滚动数组', '使用回溯搜索']),
    correct_options: JSON.stringify([2]),
    explanation: '滚动数组可以将空间复杂度由 O(nW) 降至 O(W)。',
    knowledge_point: '动态规划优化',
  },
  {
    id: 'q_politics_01',
    practice_set_id: 'practice_politics_hot',
    question_type: 'single',
    stem: '回答政治主观题时，开头需要做到哪一点才能更好引出观点？',
    options_json: JSON.stringify([
      '直接给出结论即可，不必铺垫',
      '先简要概括材料背景，再提出观点',
      '引用经典语录即可',
      '加入与主题无关的故事增加趣味性',
    ]),
    correct_options: JSON.stringify([1]),
    explanation: '开头应当概括背景并提出观点，形成完整的论述框架。',
    knowledge_point: '政治主观题作答结构',
  },
  {
    id: 'q_politics_02',
    practice_set_id: 'practice_politics_hot',
    question_type: 'multiple',
    stem: '下列哪些属于常见的时政论证素材？',
    options_json: JSON.stringify([
      '政府工作报告中的数据',
      '权威媒体对热点事件的评论',
      '个人社交平台的随意观点',
      '党的二十大报告中的战略部署',
    ]),
    correct_options: JSON.stringify([0, 1, 3]),
    explanation: '论证素材需权威可信，可引用政府报告、权威评论与大会报告。',
    knowledge_point: '时政素材积累',
  },
  {
    id: 'q_english_01',
    practice_set_id: 'practice_english_reading',
    question_type: 'single',
    stem: '长难句分析的第一步通常是？',
    options_json: JSON.stringify([
      '找到句子的谓语动词',
      '先翻译从句',
      '查阅生词',
      '寻找代词指代',
    ]),
    correct_options: JSON.stringify([0]),
    explanation: '分析长难句首先需要找出谓语动词，确定句子主干。',
    knowledge_point: '长难句分析',
  },
  {
    id: 'q_english_02',
    practice_set_id: 'practice_english_reading',
    question_type: 'multiple',
    stem: '关于英语阅读理解细节题的解题技巧，正确的有？',
    options_json: JSON.stringify([
      '定位关键词，回到原文寻找对应句子',
      '根据常识和经验选择答案即可',
      '注意同义替换与语义转换',
      '不需要通读全文，只需看题干',
    ]),
    correct_options: JSON.stringify([0, 2]),
    explanation: '细节题需要回原文定位，同时留意选项中的同义替换。',
    knowledge_point: '阅读理解技巧',
  },
];

export const practiceAttemptsSeed = [
  {
    id: 'attempt_001',
    practice_set_id: 'practice_algo_strength',
    user_id: 'user_student_1',
    accuracy: 0.68,
    score: 68,
    answers_json: JSON.stringify([
      { questionId: 'q_algo_01', selected: [2] },
      { questionId: 'q_algo_02', selected: [0, 3] },
      { questionId: 'q_algo_03', selected: [2] },
      { questionId: 'q_algo_04', selected: [0, 1] },
      { questionId: 'q_algo_05', selected: [1] },
      { questionId: 'q_algo_06', selected: [2] },
    ]),
    summary: 'AI 诊断：图论题正确率 60%，建议复盘 Dijkstra 边界条件。',
  },
  {
    id: 'attempt_002',
    practice_set_id: 'practice_english_reading',
    user_id: 'user_student_1',
    accuracy: 0.82,
    score: 82,
    answers_json: JSON.stringify([
      { questionId: 'q_english_01', selected: [0] },
      { questionId: 'q_english_02', selected: [0, 2] },
    ]),
    summary: '长难句分析准确，需关注选项干扰项的逻辑关系。',
  },
];

export const scheduleSeed = () => [
  {
    id: 'schedule_live_math',
    user_id: 'user_student_1',
    title: '数学一冲刺直播课',
    event_type: '直播课',
    start_time: dayjs().hour(19).minute(0).second(0).toISOString(),
    end_time: dayjs().hour(21).minute(0).second(0).toISOString(),
    location: '腾讯会议 938-102-001',
    focus: '线性代数特征值专项',
    tags_json: JSON.stringify(['直播课', '数学']),
  },
  {
    id: 'schedule_morning_read',
    user_id: 'user_student_1',
    title: '英语晨读打卡',
    event_type: '自习',
    start_time: dayjs().hour(6).minute(45).second(0).toISOString(),
    end_time: dayjs().hour(7).minute(25).second(0).toISOString(),
    location: '',
    focus: '外刊精读 + 词汇巩固',
    tags_json: JSON.stringify(['晨读', '英语']),
  },
  {
    id: 'schedule_evening_review',
    user_id: 'user_student_1',
    title: '晚间错题回顾',
    event_type: '自习',
    start_time: dayjs().add(1, 'day').hour(21).minute(30).second(0).toISOString(),
    end_time: dayjs().add(1, 'day').hour(22).minute(30).second(0).toISOString(),
    location: '',
    focus: '复盘图论与政治主观题',
    tags_json: JSON.stringify(['错题整理']),
  },
  {
    id: 'schedule_mock_exam',
    user_id: 'user_student_1',
    title: '英语一全真模拟',
    event_type: '模拟考试',
    start_time: dayjs().add(2, 'day').hour(13).minute(30).toISOString(),
    end_time: dayjs().add(2, 'day').hour(17).minute(0).toISOString(),
    location: '线下自习室 A301',
    focus: '完整模拟，检验时间管理',
    tags_json: JSON.stringify(['模考', '英语']),
  },
  {
    id: 'schedule_coach',
    user_id: 'user_student_1',
    title: '教练辅导：AI 诊断复盘',
    event_type: '教练辅导',
    start_time: dayjs().add(3, 'day').hour(20).minute(0).toISOString(),
    end_time: dayjs().add(3, 'day').hour(21).minute(0).toISOString(),
    location: '腾讯会议 889-345-778',
    focus: '讨论算法薄弱点训练策略',
    tags_json: JSON.stringify(['辅导', 'AI 诊断']),
  },
  {
    id: 'schedule_admin_sync',
    user_id: 'user_admin_1',
    title: '教研数据同步会',
    event_type: '教练辅导',
    start_time: dayjs().add(1, 'day').hour(10).minute(0).toISOString(),
    end_time: dayjs().add(1, 'day').hour(11).minute(0).toISOString(),
    location: '办公区会议室 B2',
    focus: '更新课程上线进度与题库状态',
    tags_json: JSON.stringify(['教研', '会议']),
  },
];

export const forumTopicsSeed = [
  {
    id: 'topic_ai_training',
    author_id: 'user_student_1',
    title: 'AI 自适应训练体验分享',
    content: '昨晚体验了 AI 自适应训练，系统自动识别了我在图论和动态规划上的薄弱知识点，题目难度衔接很顺畅。大家还有哪些使用技巧？',
    tags_json: JSON.stringify(['AI 训练', '数据结构', '经验分享']),
    needs_moderation: 0,
  },
  {
    id: 'topic_material_share',
    author_id: 'user_student_1',
    title: '求推荐：数学一冲刺资料',
    content: '有没有小伙伴整理数学一线性代数的错题本或冲刺资料？想找一份适合快速查漏补缺的。',
    tags_json: JSON.stringify(['数学', '资料交流']),
    needs_moderation: 0,
  },
  {
    id: 'topic_admin_notice',
    author_id: 'user_admin_1',
    title: '教研通知：英语写作密训营资料校对',
    content: '本周五前请完成英语写作密训营资料的交叉校对，注意关注范文点评部分的语言风格一致性。',
    tags_json: JSON.stringify(['教研', '公告']),
    needs_moderation: 1,
  },
];

export const forumCommentsSeed = [
  {
    id: 'comment_001',
    topic_id: 'topic_ai_training',
    author_id: 'user_admin_1',
    content: '很棒的反馈！建议在训练后打开知识点回放功能，查看详细解析。',
  },
  {
    id: 'comment_002',
    topic_id: 'topic_ai_training',
    author_id: 'user_student_1',
    content: '收到！另外 AI 生成的错题本也不错，可以导出 PDF。',
  },
  {
    id: 'comment_003',
    topic_id: 'topic_material_share',
    author_id: 'user_admin_1',
    content: '我们整理了一份线代冲刺资料，已上传至资料中心，可搜索“线代冲刺公式速查表”。',
  },
];

export const forumLikesSeed = [
  { topic_id: 'topic_ai_training', user_id: 'user_student_1' },
  { topic_id: 'topic_ai_training', user_id: 'user_admin_1' },
  { topic_id: 'topic_material_share', user_id: 'user_student_1' },
];

export const subjectMasterySeed = [
  {
    id: 'mastery_math',
    user_id: 'user_student_1',
    subject: '数学一',
    mastery: 0.72,
    trend: '+6.4%',
    focus: '重点复习线性代数特征值与概率统计大题。',
  },
  {
    id: 'mastery_politics',
    user_id: 'user_student_1',
    subject: '政治',
    mastery: 0.58,
    trend: '+3.1%',
    focus: '梳理毛中特第二章框架，并强化时政题积累。',
  },
  {
    id: 'mastery_english',
    user_id: 'user_student_1',
    subject: '英语一',
    mastery: 0.81,
    trend: '+4.8%',
    focus: '巩固阅读理解逻辑与写作素材积累。',
  },
  {
    id: 'mastery_cs',
    user_id: 'user_student_1',
    subject: '计算机 408',
    mastery: 0.66,
    trend: '+5.5%',
    focus: '补齐数据结构-图与操作系统-进程管理。',
  },
];

export const analyticsOverviewSeed = [
  {
    user_id: 'user_student_1',
    mock_trend: '最近 3 次模考成绩：358 → 368 → 379，已连续两周保持上升趋势。',
    time_distribution: '工作日平均每日学习 4.5 小时，周末 7 小时。建议将政治复习时间提升 30%。',
    behavior_insight: '上周平均专注时长 42min/番茄钟，错题回顾完成率 86%，夜间复盘坚持 5/7 天。',
  },
];

export const weakTopicsSeed = [
  {
    id: 'weak_linear_algebra',
    user_id: 'user_student_1',
    topic: '线性代数 · 特征值与特征向量',
    error_rate: '32%',
    suggestion: '回看第 5-6 讲并完成配套训练营。',
  },
  {
    id: 'weak_politics',
    user_id: 'user_student_1',
    topic: '政治 · 马原哲学部分',
    error_rate: '28%',
    suggestion: '整理错题思维导图，参加周五直播答疑。',
  },
  {
    id: 'weak_english',
    user_id: 'user_student_1',
    topic: '英语 · 长难句理解',
    error_rate: '25%',
    suggestion: '每日精读一篇外刊，积累结构。',
  },
  {
    id: 'weak_os',
    user_id: 'user_student_1',
    topic: '操作系统 · 进程同步',
    error_rate: '24%',
    suggestion: '完成专项题单并观看讲解视频。',
  },
  {
    id: 'weak_graph',
    user_id: 'user_student_1',
    topic: '数据结构 · 图的遍历',
    error_rate: '21%',
    suggestion: '整理 DFS/BFS 思维流程图，强化练习。',
  },
];
